# coding: utf-8

"""
    cambioml-sec-agent-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sec_agent_sdk.models.filing_table import FilingTable

class TestFilingTable(unittest.TestCase):
    """FilingTable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilingTable(self):
        """Test FilingTable"""
        # inst = FilingTable()

if __name__ == '__main__':
    unittest.main()
