# coding: utf-8

"""
    sec-agent-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sec_agent_sdk.models.create_filing import CreateFiling

class TestCreateFiling(unittest.TestCase):
    """CreateFiling unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateFiling:
        """Test CreateFiling
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFiling`
        """
        model = CreateFiling()
        if include_optional:
            return CreateFiling(
                company = '',
                cik = '',
                quarter = '',
                date_filed = '',
                url = '',
                form_type = '',
                table = '',
                parsed = ''
            )
        else:
            return CreateFiling(
                company = '',
                date_filed = '',
                form_type = '',
                table = '',
                parsed = '',
        )
        """

    def testCreateFiling(self):
        """Test CreateFiling"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
