# coding: utf-8

"""
    sec-agent-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sec_agent_sdk.models.form_type import FormType

class TestFormType(unittest.TestCase):
    """FormType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFormType(self):
        """Test FormType"""
        # inst = FormType()

if __name__ == '__main__':
    unittest.main()
