# coding: utf-8

"""
    sec-agent-api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class FormType(str, Enum):
    """
    FormType
    """

    """
    allowed enum values
    """
    TEN_Q = "10-Q"
    TEN_K = "10-K"
    EIGHT_K = "8-K"
    SIX_K = "6-K"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FormType from a JSON string"""
        return cls(json.loads(json_str))
